{% set name = "OpenMiChroM" %}
{% set version = "1.1.0" %}
{% set data = load_json('https://pypi.org/pypi/{{ name }}/{{ version }}/json') %}
{% set sdist = data['urls'] | selectattr('packagetype', 'equalto', 'sdist') | first %}
{% set url = sdist['url'] %}
{% set sha256 = sdist['digests']['sha256'] %}

package:
  name: {{ name|lower }}  # conda-forge prefers lowercase package names
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python  # Indicates a pure Python package
  number: 0
  entry_points:
    - CLINAME=OpenMiChroM._cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - openmm
    - h5py
    - numpy
    - pandas
    - python
    - scikit-learn
    - scipy


test:
  imports:
    - OpenMiChroM
    - tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ndb.rice.edu/Open-MiChroM
  summary: Open-Michrom lib for chromosome simulations
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://open-michrom.readthedocs.io
  dev_url: https://github.com/junioreif/OpenMiChroM

extra:
  recipe-maintainers:
    - junioreif
