{% set name = "OpenMiChroM" %}
{% set version = "1.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/OpenMiChroM-{{ version }}.tar.gz
  sha256: 796ca4dfd1bb0ebe762fa5e773f93909a50f0f10aaed496d5e8c64b8c1a54099

build:
  number: 0
  noarch: python
  entry_points:
    - CLINAME=OpenMiChroM._cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - h5py
    - numpy
    - pandas
    - python >=3.6
    - scikit-learn
    - scipy
    - six
    - openmm

test:
  imports:
    - OpenMiChroM
    - tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ndb.rice.edu/Open-MiChroM
  summary: Open-Michrom lib for chromosome simulations
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://open-michrom.readthedocs.io
  dev_url: https://github.com/junioreif/OpenMiChroM

extra:
  recipe-maintainers:
    - junioreif
