schema_version: 1

context:
  name: OpenMiChroM
  version: 1.1.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/e9/b3/03e1da409c03cfa7e15313e9be84f566fa73c7a7f610fa2782ce899efc9b/openmichrom-1.1.1.tar.gz
  sha256: 21b6fa2d345adef1ec3253b5e7e4ce5388e85220acca04ab4472290a0d524ec8

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - CLINAME=OpenMiChroM._cli:main

requirements:
  host:
    - openmm
    - h5py
    - numpy
    - pandas
    - pip
    - python ${{ python_min }}
    - scikit-learn
    - scipy
  run:
    - openmm
    - h5py
    - numpy
    - pandas
    - python >=${{ python_min }}
    - scikit-learn
    - scipy

tests:
  - python:
      imports:
        - OpenMiChroM
  - requirements:
      run:
        - python ${{ python_min }}

about:
  summary: Open-Michrom lib for chromosome simulations
  license: MIT
  license_file: LICENSE
  homepage: https://ndb.rice.edu/Open-MiChroM
  repository: https://github.com/junioreif/OpenMiChroM
  documentation: https://open-michrom.readthedocs.io

extra:
  recipe-maintainers:
    - junioreif
